function [vParams vToe] = getParams()


paramList;

vParams = [G,Jxx1,Jxx2,...
             Jyy1,Jyy2,...
             Jzz1,Jzz2,...
             K1ax,K1ay,K1az,...
             K1brx,K1bry,K1bx,K1by,K1bz,...
             K1crz,K1cx,K1cy,K1cz,...
             K2ax,K2ay,K2az,...
             aF,aH,...
             cF,cH,...
             dyVel,...
             kF,kH,...
             m1,m2,...
             mud,mus,...
             nx,ny,nz,...
             pF,pH,...
             rF,rH,...
             stVel,...
             sx,sy,sz,...
             t1x,t1y,t1z,...
             t2x,t2y,t2z]';
         
vToe = [kmt, dmt, thOff];